CREATE TABLE APPLICATION_METADATA (
    KEY VARCHAR (1024) PRIMARY KEY NOT NULL UNIQUE,
    VALUE TEXT
);

CREATE TABLE TEXT_ENTRY (
    UUID VARCHAR (60) PRIMARY KEY
              NOT NULL
              UNIQUE,
    TIME VARCHAR (23) NOT NULL,
    NAME TEXT NOT NULL
);

CREATE TABLE TEXT_ENTRY_METADATA (
    TEXT_ENTRY_UUID VARCHAR (60) NOT NULL,
    KEY VARCHAR (1024) NOT NULL,
    VALUE TEXT,
    PRIMARY KEY (TEXT_ENTRY_UUID, KEY)
);

INSERT INTO APPLICATION_METADATA (KEY, VALUE) VALUES ('database.version', '1');